python kNN_decoder.py -snr 0 -w 10 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 10 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 10 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 10 -csv results_md.csv
python kNN_decoder.py -snr 0 -w 20 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 20 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 20 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 20 -csv results_md.csv
python kNN_decoder.py -snr 0 -w 30 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 30 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 30 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 30 -csv results_md.csv
python kNN_decoder.py -snr 0 -w 40 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 40 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 40 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 40 -csv results_md.csv
python kNN_decoder.py -snr 0 -w 50 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 50 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 50 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 50 -csv results_md.csv
python kNN_decoder.py -snr 0 -w 60 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 60 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 60 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 60 -csv results_md.csv
python kNN_decoder.py -snr 0 -w 70 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 70 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 70 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 70 -csv results_md.csv
python kNN_decoder.py -snr 0 -w 80 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 80 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 80 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 80 -csv results_md.csv
python kNN_decoder.py -snr 0 -w 90 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 90 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 90 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 90 -csv results_md.csv
python kNN_decoder.py -snr 0 -w 100 -csv results_md.csv
python kNN_decoder.py -snr 5 -w 100 -csv results_md.csv
python kNN_decoder.py -snr 10 -w 100 -csv results_md.csv
python kNN_decoder.py -snr 15 -w 100 -csv results_md.csv
