python kNN_decoder.py -snr 0 -w 10 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 10 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 10 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 0 -w 20 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 20 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 20 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 0 -w 30 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 30 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 30 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 0 -w 40 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 40 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 40 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 0 -w 50 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 50 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 50 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 0 -w 60 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 60 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 60 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 0 -w 70 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 70 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 70 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 0 -w 80 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 80 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 80 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 0 -w 90 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 90 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 90 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 0 -w 100 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 5 -w 100 -k 3 -csv results_knn3.csv
python kNN_decoder.py -snr 10 -w 100 -k 3 -csv results_knn3.csv
