python MINE_Decoder.py -snr 0 -w 10 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 10 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 10 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 10 -csv unique_rates.csv
python MINE_Decoder.py -snr 0 -w 20 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 20 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 20 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 20 -csv unique_rates.csv
python MINE_Decoder.py -snr 0 -w 30 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 30 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 30 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 30 -csv unique_rates.csv
python MINE_Decoder.py -snr 0 -w 40 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 40 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 40 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 40 -csv unique_rates.csv
python MINE_Decoder.py -snr 0 -w 50 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 50 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 50 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 50 -csv unique_rates.csv
python MINE_Decoder.py -snr 0 -w 60 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 60 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 60 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 60 -csv unique_rates.csv
python MINE_Decoder.py -snr 0 -w 70 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 70 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 70 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 70 -csv unique_rates.csv
python MINE_Decoder.py -snr 0 -w 80 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 80 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 80 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 80 -csv unique_rates.csv
python MINE_Decoder.py -snr 0 -w 90 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 90 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 90 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 90 -csv unique_rates.csv
python MINE_Decoder.py -snr 0 -w 100 -csv unique_rates.csv
python MINE_Decoder.py -snr 5 -w 100 -csv unique_rates.csv
python MINE_Decoder.py -snr 10 -w 100 -csv unique_rates.csv
python MINE_Decoder.py -snr 15 -w 100 -csv unique_rates.csv
