python MINE_Decoder.py -snr 0 -w 10
python MINE_Decoder.py -snr 5 -w 10
python MINE_Decoder.py -snr 10 -w 10
python MINE_Decoder.py -snr 15 -w 10
python MINE_Decoder.py -snr 0 -w 20
python MINE_Decoder.py -snr 5 -w 20
python MINE_Decoder.py -snr 10 -w 20
python MINE_Decoder.py -snr 15 -w 20
python MINE_Decoder.py -snr 0 -w 30
python MINE_Decoder.py -snr 5 -w 30
python MINE_Decoder.py -snr 10 -w 30
python MINE_Decoder.py -snr 15 -w 30
python MINE_Decoder.py -snr 0 -w 40
python MINE_Decoder.py -snr 5 -w 40
python MINE_Decoder.py -snr 10 -w 40
python MINE_Decoder.py -snr 15 -w 40
python MINE_Decoder.py -snr 0 -w 50
python MINE_Decoder.py -snr 5 -w 50
python MINE_Decoder.py -snr 10 -w 50
python MINE_Decoder.py -snr 15 -w 50
python MINE_Decoder.py -snr 0 -w 60
python MINE_Decoder.py -snr 5 -w 60
python MINE_Decoder.py -snr 10 -w 60
python MINE_Decoder.py -snr 15 -w 60
python MINE_Decoder.py -snr 0 -w 70
python MINE_Decoder.py -snr 5 -w 70
python MINE_Decoder.py -snr 10 -w 70
python MINE_Decoder.py -snr 15 -w 70
python MINE_Decoder.py -snr 0 -w 80
python MINE_Decoder.py -snr 5 -w 80
python MINE_Decoder.py -snr 10 -w 80
python MINE_Decoder.py -snr 15 -w 80
python MINE_Decoder.py -snr 0 -w 90
python MINE_Decoder.py -snr 5 -w 90
python MINE_Decoder.py -snr 10 -w 90
python MINE_Decoder.py -snr 15 -w 90
